### ISSUE TITLE
Internal Vim crash on file write: E315

### ISSUE THREAD

**Issue by timonson** [RRethy/vim-hexokinase#34]
Regarding: https://github.com/RRethy/vim-hexokinase/issues/32

I updated hexokinase but the following error still occurs:

When turned off and while saving a file I still get this error on vim: `E315: ml_get: invalid lnum: 39` and after that hexokinase is turned on automatically.

**Comment by RRethy** [comment]
That's an internal error in Vim. Not sure what's the cause. Can you post a file where it occurs and the exact sequence of commands.

**Comment by timonson** [comment]
It happens for example with the following code saved in a **css** file. The command is *save file*, for example `:w<cr>` or `ZZ`  or  any other way.
It might be that some plugin somehow intervenes but I am no vim expert to be honest. I disabled all my syntax plugins but still got this error. Maybe somebody else can confirm this error?

```css
:root {
  box-sizing: border-box;
}
*,
::before,
::after {
  box-sizing: inherit;
}
body {
  background-color: #eee;
  font-family: Helvetica, Arial, sans-serif;
  border: red;
}
header {
  color: #fff;
  background-color: #0072b0;
  border-radius: 0.5em;
}
main {
  display: block;
}
```
