### ISSUE TITLE
Highlighting not showing on Windows

### ISSUE THREAD

**Issue by Shaedil** [RRethy/vim-hexokinase#82]
### Issue
![image](https://user-images.githubusercontent.com/17773568/115612397-36fafd00-a2b9-11eb-9527-c8a225f1d54f.png)

Highlights do not show at all

### Version
Running Neovim on Windows 10 via GUI, but issue persists in TUI
![image](https://user-images.githubusercontent.com/17773568/115611792-8ab91680-a2b8-11eb-8581-75b532ee2321.png)
`go version go1.16.3 windows/amd64`
Ran `make hexokinase` in plugin directory with no issues

### Reproducible vimrc

```vim
call plug#begin('~/.vim/plugged')
Plug 'RRethy/vim-hexokinase', {'do': 'make hexokinase'}
call plug#end()

filetype plugin on
syntax on
set nocompatible
set encoding=utf8
set termguicolors
colorscheme gruvbox
set background=dark
let g:Hexokinase_highlighters = ['virtual']
```

```css
body {
	background-color: #e8eaf6;
	background-color: deeppink;
	background-color: #f00;
	background-color: oRaNgE;
	background-color: rgb(255, 255, 0);
	background-color: rgba(0, 128, 0, 1);
	background-color: hsl(174,72.1%,56.5%);
	background-color: hsla(274.6,100%,25.5%, 1);
	background-color: #ee82ee;
}
```
